<a href="https://colab.research.google.com/github/j0seph-gp/road-accident-black-spot-analysis/blob/main/Road_Accident_Black_Spot_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import platform
import subprocess

print("Operating System:")
print(platform.platform())

print("\nJava version:")
result = subprocess.run(
    ["java", "-version"],
    capture_output=True,
    text=True
)
print(result.stderr)

Operating System:
Linux-6.6.122+-x86_64-with-glibc2.39

Java version:
openjdk version "21.0.12" 2026-07-21
OpenJDK Runtime Environment (build 21.0.12+8-1-24.04-Ubuntu)
OpenJDK 64-Bit Server VM (build 21.0.12+8-1-24.04-Ubuntu, mixed mode, sharing)

CHECKING HADOOP INSTALLED OR NOT ?

In [2]:
!hadoop version

/bin/bash: line 1: hadoop: command not found

Installing Hadoop

In [3]:
!wget -q https://archive.apache.org/dist/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz
!tar -xzf hadoop-3.3.6.tar.gz
!mv hadoop-3.3.6 /content/hadoop

print("Hadoop files downloaded and extracted successfully.")

Hadoop files downloaded and extracted successfully.

STEP 5 — Set Hadoop environment variables

Now we need to tell Colab where Hadoop is installed.

In [4]:
import os

os.environ["HADOOP_HOME"] = "/content/hadoop"
os.environ["HADOOP_CONF_DIR"] = "/content/hadoop/etc/hadoop"
os.environ["PATH"] = os.environ["HADOOP_HOME"] + "/bin:" + os.environ["PATH"]

print("HADOOP_HOME =", os.environ["HADOOP_HOME"])
print("HADOOP_CONF_DIR =", os.environ["HADOOP_CONF_DIR"])

HADOOP_HOME = /content/hadoop
HADOOP_CONF_DIR = /content/hadoop/etc/hadoop

STEP 6 — Verify Hadoop installation

In [5]:
!$HADOOP_HOME/bin/hadoop version

ERROR: JAVA_HOME is not set and could not be found.

STEP 6 — Set JAVA_HOME

Run only this code in a new Colab cell:

In [6]:
import os

java_home = "/usr/lib/jvm/java-21-openjdk-amd64"

os.environ["JAVA_HOME"] = java_home
os.environ["PATH"] = (
    os.environ["JAVA_HOME"] + "/bin:"
    + os.environ["HADOOP_HOME"] + "/bin:"
    + os.environ["PATH"]
)

print("JAVA_HOME =", os.environ["JAVA_HOME"])

JAVA_HOME = /usr/lib/jvm/java-21-openjdk-amd64

In [7]:
!$JAVA_HOME/bin/java -version

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
openjdk version "21.0.12" 2026-07-21
OpenJDK Runtime Environment (build 21.0.12+8-1-24.04-Ubuntu)
OpenJDK 64-Bit Server VM (build 21.0.12+8-1-24.04-Ubuntu, mixed mode, sharing)

In [8]:
!$HADOOP_HOME/bin/hadoop version

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Hadoop 3.3.6
Source code repository https://github.com/apache/hadoop.git -r 1be78238728da9266a4f88195058f08fd012bf9c
Compiled by ubuntu on 2023-06-18T08:22Z
Compiled on platform linux-x86_64
Compiled with protoc 3.7.1
From source with checksum 5652179ad55f76cb287d9c633bb53bbd
This command was run using /content/hadoop/share/hadoop/common/hadoop-common-3.3.6.jar

In [9]:
import os

hadoop_env = "/content/hadoop/etc/hadoop/hadoop-env.sh"

with open(hadoop_env, "r") as f:
    content = f.read()

java_line = 'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64'

if "export JAVA_HOME=" in content:
    lines = content.splitlines()
    lines = [
        java_line if line.strip().startswith("export JAVA_HOME=") else line
        for line in lines
    ]
    content = "\n".join(lines) + "\n"
else:
    content += "\n" + java_line + "\n"

with open(hadoop_env, "w") as f:
    f.write(content)

print("JAVA_HOME configured in hadoop-env.sh")

JAVA_HOME configured in hadoop-env.sh

In [10]:
!$HADOOP_HOME/bin/hadoop version

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Hadoop 3.3.6
Source code repository https://github.com/apache/hadoop.git -r 1be78238728da9266a4f88195058f08fd012bf9c
Compiled by ubuntu on 2023-06-18T08:22Z
Compiled on platform linux-x86_64
Compiled with protoc 3.7.1
From source with checksum 5652179ad55f76cb287d9c633bb53bbd
This command was run using /content/hadoop/share/hadoop/common/hadoop-common-3.3.6.jar

In [11]:
!$HADOOP_HOME/bin/hdfs version

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.003s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Hadoop 3.3.6
Source code repository https://github.com/apache/hadoop.git -r 1be78238728da9266a4f88195058f08fd012bf9c
Compiled by ubuntu on 2023-06-18T08:22Z
Compiled on platform linux-x86_64
Compiled with protoc 3.7.1
From source with checksum 5652179ad55f76cb287d9c633bb53bbd
This command was run using /content/hadoop/share/hadoop/common/hadoop-common-3.3.6.jar

In [12]:
import os

hadoop_conf = "/content/hadoop/etc/hadoop"

core_site = """<?xml version="1.0"?>
<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value>hdfs://localhost:9000</value>
    </property>
</configuration>
"""

with open(f"{hadoop_conf}/core-site.xml", "w") as f:
    f.write(core_site)

print("core-site.xml configured successfully.")

core-site.xml configured successfully.

In [13]:
import os

hadoop_conf = "/content/hadoop/etc/hadoop"

hdfs_site = """<?xml version="1.0"?>
<configuration>
    <property>
        <name>dfs.replication</name>
        <value>1</value>
    </property>

    <property>
        <name>dfs.namenode.name.dir</name>
        <value>file:///content/hadoop_data/namenode</value>
    </property>

    <property>
        <name>dfs.datanode.data.dir</name>
        <value>file:///content/hadoop_data/datanode</value>
    </property>
</configuration>
"""

with open(f"{hadoop_conf}/hdfs-site.xml", "w") as f:
    f.write(hdfs_site)

print("hdfs-site.xml configured successfully.")

hdfs-site.xml configured successfully.

In [14]:
!$HADOOP_HOME/bin/hdfs namenode -format -force

WARNING: /content/hadoop/logs does not exist. Creating.
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
2026-09-12 06:32:53,116 INFO namenode.NameNode: STARTUP_MSG:
/************************************************************
STARTUP_MSG: Starting NameNode
STARTUP_MSG:   host = cab95c258577/172.28.0.12
STARTUP_MSG:   args = [-format, -force]
STARTUP_MSG:   version = 3.3.6

STEP 14 — Start HDFS

Run only this cell:

In [15]:
!$HADOOP_HOME/sbin/start-dfs.sh

Starting namenodes on [[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
localhost]
ERROR: Attempting to operate on hdfs namenode as root
ERROR: but there is no HDFS_NAMENODE_USER defined. Aborting operation.
Starting datanodes
ERROR: Attempting to operate on hdfs datanode as root
ERROR: but there is no HDFS_DATANODE_USER defined. Aborting operation.
WARNING: Highly available NameNode is configured.
WARNING: Skipping SecondaryNameNode.
Starting journal nodes [[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate]
ERROR: Attempting to operate on hdfs journalnode as root
ERROR: but there is no HDFS_JOURNALNODE_USER defined. Aborting operation.

In [16]:
import os

hadoop_env = "/content/hadoop/etc/hadoop/hadoop-env.sh"

with open(hadoop_env, "r") as f:
    content = f.read()

settings = """
export HDFS_NAMENODE_USER=root
export HDFS_DATANODE_USER=root
export HDFS_SECONDARYNAMENODE_USER=root
export HDFS_JOURNALNODE_USER=root
export HDFS_ZKFC_USER=root
"""

if "HDFS_NAMENODE_USER=root" not in content:
    content += settings

with open(hadoop_env, "w") as f:
    f.write(content)

print("HDFS user configuration added successfully.")

HDFS user configuration added successfully.

In [17]:
!$HADOOP_HOME/sbin/start-dfs.sh

Starting namenodes on [[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
localhost]
ERROR: JAVA_HOME is not set and could not be found.
Starting datanodes
ERROR: JAVA_HOME is not set and could not be found.
WARNING: Highly available NameNode is configured.
WARNING: Skipping SecondaryNameNode.
Starting journal nodes [[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate]
ERROR: JAVA_HOME is not set and could not be found.

In [18]:
import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-21-openjdk-amd64"
os.environ["HADOOP_HOME"] = "/content/hadoop"
os.environ["HADOOP_CONF_DIR"] = "/content/hadoop/etc/hadoop"

print("JAVA_HOME =", os.environ["JAVA_HOME"])
print("HADOOP_HOME =", os.environ["HADOOP_HOME"])

JAVA_HOME = /usr/lib/jvm/java-21-openjdk-amd64
HADOOP_HOME = /content/hadoop

In [19]:
import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-21-openjdk-amd64"

os.system(
    "export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && "
    "/content/hadoop/sbin/start-dfs.sh"
)

768

In [20]:
!jps

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
2356 Jps

In [21]:
!grep -E "JAVA_HOME|HDFS_.*_USER" /content/hadoop/etc/hadoop/hadoop-env.sh

#  JAVA_HOME=/usr/java/testing hdfs dfs -ls
# Technically, the only required environment variable is JAVA_HOME.
# export JAVA_HOME=
# export HDFS_DATANODE_SECURE_USER=hdfs
# export HDFS_NFS3_SECURE_USER=nfsserver
# export HDFS_NAMENODE_USER=hdfs
export HDFS_NAMENODE_USER=root
export HDFS_DATANODE_USER=root
export HDFS_SECONDARYNAMENODE_USER=root
export HDFS_JOURNALNODE_USER=root
export HDFS_ZKFC_USER=root

In [22]:
hadoop_env = "/content/hadoop/etc/hadoop/hadoop-env.sh"

with open(hadoop_env, "r") as f:
    content = f.read()

# Remove any existing active JAVA_HOME line
lines = [
    line for line in content.splitlines()
    if not line.strip().startswith("export JAVA_HOME=")
]

# Add the correct Java path
lines.append("export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64")

with open(hadoop_env, "w") as f:
    f.write("\n".join(lines) + "\n")

print("JAVA_HOME added to hadoop-env.sh")

JAVA_HOME added to hadoop-env.sh

In [23]:
!grep "export JAVA_HOME=" /content/hadoop/etc/hadoop/hadoop-env.sh

# export JAVA_HOME=
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

In [24]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HADOOP_CONF_DIR=/content/hadoop/etc/hadoop && \
/content/hadoop/sbin/start-dfs.sh

Starting namenodes on [[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
localhost]
sed: -e expression #1, char 7: unknown option to `s'
[0.001s][warning][os,container]: hostname contains invalid characters
Cgroup: ssh: Could not resolve hostname cgroup: Name or service not known
at: ssh: Could not resolve hostname at: No address associated with hostname
to: ssh: Could not resolve hostname to: No address associated with hostname
path: ssh: Could not resolve hostname path: Name or service not known
seems: ssh: Could not resolve hostname seems: Name or service not known
controller: ssh: Could not resolve hostname controller: Name or service not known
memory: ssh: Could not resolve hostname memory: Name or service not known
have: ssh: Could not resolve hostname have: Name or service not known
sed: -e expression #1, char 7: unknown option to `s'
won't: hostname contains invalid characters
[0.001s][warning][os,container]: hostname contains invalid characters
to: ssh: Could not resolve hostname to: No address associated with hostname
Cgroup: ssh: Could not resolve hostname cgroup: Name or service not known
be: ssh: Could not resolve hostname be: No address associated with hostname
limits: ssh: Could not resolve hostname limits: Name or service not known
moved: ssh: Could not resolve hostname moved: Name or service not known
accurate: ssh: Could not resolve hostname accurate: Name or service not known
detected: ssh: Could not resolve hostname detected: Name or service not known
sed: -e expression #1, char 7: unknown option to `s'
controller: ssh: Could not resolve hostname controller: Name or service not known
to: ssh: Could not resolve hostname to: No address associated with hostname
moved: ssh: Could not resolve hostname moved: Name or service not known
path: ssh: Could not resolve hostname path: Name or service not known
at: ssh: Could not resolve hostname at: No address associated with hostname
to: ssh: Could not resolve hostname to: No address associated with hostname
have: ssh: Could not resolve hostname have: Name or service not known
seems: ssh: Could not resolve hostname seems: Name or service not known
cpu: ssh: Could not resolve hostname cpu: Name or service not known
sed: -e expression #1, char 7: unknown option to `s'
won't: hostname contains invalid characters
localhost: ssh: connect to host localhost port 22: Connection refused
limits: ssh: Could not resolve hostname limits: Name or service not known
detected: ssh: Could not resolve hostname detected: Name or service not known
be: ssh: Could not resolve hostname be: No address associated with hostname
accurate: ssh: Could not resolve hostname accurate: Name or service not known
Starting datanodes
localhost: ssh: connect to host localhost port 22: Connection refused
WARNING: Highly available NameNode is configured.
WARNING: Skipping SecondaryNameNode.
Starting journal nodes [[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate]
sed: -e expression #1, char 7: unknown option to `s'
[0.001s][warning][os,container]: hostname contains invalid characters
path: ssh: Could not resolve hostname path: Name or service not known
at: ssh: Could not resolve hostname at: No address associated with hostname
Cgroup: ssh: Could not resolve hostname cgroup: Name or service not known
memory: ssh: Could not resolve hostname memory: Name or service not known
controller: ssh: Could not resolve hostname controller: Name or service not known
to: ssh: Could not resolve hostname to: No address associated with hostname
seems: ssh: Could not resolve hostname seems: Name or service not known
have: ssh: Could not resolve hostname have: Name or service not known
sed: -e expression #1, char 7: unknown option to `s'
limits: ssh: Could not resolve hostname limits: Name or service not known
accurate: ssh: Could not resolve hostname accurate: Name or service not known
moved: ssh: Could not resolve hostname moved: Name or service not known
[0.001s][warning][os,container]: hostname contains invalid characters
won't: hostname contains invalid characters
to: ssh: Could not resolve hostname to: No address associated with hostname
detected: ssh: Could not resolve hostname detected: Name or service not known
be: ssh: Could not resolve hostname be: No address associated with hostname
Cgroup: ssh: Could not resolve hostname cgroup: Name or service not known
sed: -e expression #1, char 7: unknown option to `s'
to: ssh: Could not resolve hostname to: No address associated with hostname
have: ssh: Could not resolve hostname have: Name or service not known
moved: ssh: Could not resolve hostname moved: Name or service not known
path: ssh: Could not resolve hostname path: Name or service not known
at: ssh: Could not resolve hostname at: No address associated with hostname
to: ssh: Could not resolve hostname to: No address associated with hostname
cpu: ssh: Could not resolve hostname cpu: Name or service not known
seems: ssh: Could not resolve hostname seems: Name or service not known
controller: ssh: Could not resolve hostname controller: Name or service not known
sed: -e expression #1, char 7: unknown option to `s'
won't: hostname contains invalid characters
detected: ssh: Could not resolve hostname detected: Name or service not known
be: ssh: Could not resolve hostname be: No address associated with hostname
limits: ssh: Could not resolve hostname limits: Name or service not known
accurate: ssh: Could not resolve hostname accurate: Name or service not known

In [25]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-21-openjdk-amd64"

!$HADOOP_HOME/bin/hdfs --daemon start namenode

In [26]:
!jps

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
2929 NameNode
2966 Jps

In [27]:
import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-21-openjdk-amd64"

!$HADOOP_HOME/bin/hdfs --daemon start datanode

In [28]:
!jps

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
3025 DataNode
2929 NameNode
3061 Jps

In [29]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -ls /

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.002s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate

In [30]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -ls / ; \
echo "Exit code: $?"

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Exit code: 0

In [31]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -mkdir -p /road_accidents

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate

In [32]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -ls /

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Found 1 items
drwxr-xr-x   - root supergroup          0 2026-09-12 06:33 /road_accidents

In [33]:
!ls -lh /content

total 697M
drwxr-xr-x 11 ubuntu ubuntu 4.0K Sep 12 06:32 hadoop
-rw-r--r--  1 root   root   697M Jun 25  2023 hadoop-3.3.6.tar.gz
drwxr-xr-x  4 root   root   4.0K Sep 12 06:33 hadoop_data
drwxr-xr-x  1 root   root   4.0K Sep  4 13:25 sample_data

In [34]:
from google.colab import files

uploaded = files.upload()

Saving accident_dataset.csv to accident_dataset.csv

In [35]:
import pandas as pd

df = pd.read_csv("/content/accident_dataset.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))
print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Rows: 3500
Columns: 11

Column names:
['latitude', 'longitude', 'hour', 'temperature', 'visibility', 'traffic_density', 'weather', 'road_type', 'weekend', 'peak_hour', 'risk_score']

First 5 rows:

,latitude,longitude,hour,temperature,visibility,traffic_density,weather,road_type,weekend,peak_hour,risk_score
0,13.014856,77.553069,14,14.2,2,2,0,1,0,0,0.7520
1,13.039986,77.612158,19,27.4,1,0,0,2,0,1,0.5782
2,12.905146,77.742477,10,36.7,1,2,2,1,1,1,0.9800
3,12.953085,77.545456,4,40.4,2,2,0,0,0,0,0.8665
4,12.916933,77.603683,0,15.2,2,0,0,0,0,0,0.7057

In [36]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -put -f /content/accident_dataset.csv /road_accidents/

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate

In [37]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -ls -h /road_accidents/

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Found 1 items
-rw-r--r--   1 root supergroup    159.9 K 2026-09-12 06:34 /road_accidents/accident_dataset.csv

In [38]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -cat /road_accidents/accident_dataset.csv | head -5

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
latitude,longitude,hour,temperature,visibility,traffic_density,weather,road_type,weekend,peak_hour,risk_score
13.014856,77.553069,14,14.2,2,2,0,1,0,0,0.752
13.039986,77.612158,19,27.4,1,0,0,2,0,1,0.5782
cat: Unable to write to output stream.

In [39]:
!hive --version

/bin/bash: line 1: hive: command not found

In [40]:
!wget -q https://archive.apache.org/dist/hive/hive-3.1.3/apache-hive-3.1.3-bin.tar.gz
!tar -xzf apache-hive-3.1.3-bin.tar.gz
!mv apache-hive-3.1.3-bin /content/hive

print("Hive downloaded and extracted successfully.")

Hive downloaded and extracted successfully.

In [41]:
import os

os.environ["HIVE_HOME"] = "/content/hive"
os.environ["PATH"] = (
    os.environ["HIVE_HOME"] + "/bin:"
    + os.environ["PATH"]
)

print("HIVE_HOME =", os.environ["HIVE_HOME"])

HIVE_HOME = /content/hive

In [42]:
!$HIVE_HOME/bin/hive --version

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive 3.1.3
Git git://MacBook-Pro.fios-router.home/Users/ngangam/commit/hive -r 4df4d75bf1e16fe0af75aad0b4179c34c07fc975
Compiled by ngangam on Sun Apr 3 16:58:16 EDT 2022
From source with checksum 5da234766db5dfbe3e92926c9bbab2af

In [43]:
!mkdir -p /content/hive_warehouse
!mkdir -p /content/hive_tmp

print("Hive warehouse and temporary directories created.")

Hive warehouse and temporary directories created.

In [44]:
hive_conf = "/content/hive/conf/hive-site.xml"

hive_site = """<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:derby:;databaseName=/content/hive_metastore_db;create=true</value>
    </property>

    <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>hdfs://localhost:9000/user/hive/warehouse</value>
    </property>

    <property>
        <name>hive.exec.scratchdir</name>
        <value>hdfs://localhost:9000/tmp/hive</value>
    </property>

</configuration>
"""

with open(hive_conf, "w") as f:
    f.write(hive_site)

print("Hive configuration created successfully.")

Hive configuration created successfully.

In [45]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -mkdir -p /user/hive/warehouse && \
/content/hadoop/bin/hdfs dfs -mkdir -p /tmp/hive

print("Hive HDFS directories created successfully.")

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Hive HDFS directories created successfully.

In [46]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
/content/hadoop/bin/hdfs dfs -ls /user/hive/

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
Found 1 items
drwxr-xr-x   - root supergroup          0 2026-09-12 06:34 /user/hive/warehouse

In [47]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
export HIVE_HOME=/content/hive && \
/content/hive/bin/hive -e "SHOW DATABASES;"

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = 4a576757-9c70-4b3e-82a0-587f6c080059
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:413)
	at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:389)
	at org.apache.hadoop.hive.cli.CliSessionState.<init>(CliSessionState.java:60)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:705)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:683)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:328)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:241)

In [48]:
!ls -d /usr/lib/jvm/* | grep -E "java-11|jdk-11"

In [49]:
!apt-get update -qq
!apt-get install -y openjdk-11-jdk -qq

print("Java 11 installation completed.")

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package at-spi2-common.
(Reading database ... 122797 files and directories currently installed.)
Preparing to unpack .../00-at-spi2-common_2.52.0-1build1_all.deb ...
Unpacking at-spi2-common (2.52.0-1build1) ...
Selecting previously unselected package libatspi2.0-0t64:amd64.
Preparing to unpack .../01-libatspi2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../02-libxtst6_2%3a1.2.3-1.1build1_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1.1build1) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../03-session-migration_0.3.9build1_amd64.deb ...
Unpacking session-migration (0.3.9build1) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../04-gsettings-desktop-schemas_46.1-0ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (46.1-0ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../05-at-spi2-core_2.52.0-1build1_amd64.deb ...
Unpacking at-spi2-core (2.52.0-1build1) ...
Selecting previously unselected package fonts-dejavu-mono.
Preparing to unpack .../06-fonts-dejavu-mono_2.37-8_all.deb ...
Unpacking fonts-dejavu-mono (2.37-8) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../07-fonts-dejavu-core_2.37-8_all.deb ...
Unpacking fonts-dejavu-core (2.37-8) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../08-fonts-dejavu-extra_2.37-8_all.deb ...
Unpacking fonts-dejavu-extra (2.37-8) ...
Selecting previously unselected package libatk1.0-0t64:amd64.
Preparing to unpack .../09-libatk1.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libatk-bridge2.0-0t64:amd64.
Preparing to unpack .../10-libatk-bridge2.0-0t64_2.52.0-1build1_amd64.deb ...
Unpacking libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../11-libxcomposite1_1%3a0.4.5-1build3_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build3) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../12-libxxf86dga1_2%3a1.1.5-1build1_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-1build1) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../13-x11-utils_7.7+6build2_amd64.deb ...
Unpacking x11-utils (7.7+6build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../14-libatk-wrapper-java_0.40.0-3build2_all.deb ...
Unpacking libatk-wrapper-java (0.40.0-3build2) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../15-libatk-wrapper-java-jni_0.40.0-3build2_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.40.0-3build2) ...
Selecting previously unselected package libxt-dev:amd64.
Preparing to unpack .../16-libxt-dev_1%3a1.2.1-1.2build1_amd64.deb ...
Unpacking libxt-dev:amd64 (1:1.2.1-1.2build1) ...
Selecting previously unselected package openjdk-11-jre-headless:amd64.
Preparing to unpack .../17-openjdk-11-jre-headless_11.0.32+9-1ubuntu1~24.04_amd64.deb ...
Unpacking openjdk-11-jre-headless:amd64 (11.0.32+9-1ubuntu1~24.04) ...
Selecting previously unselected package openjdk-11-jre:amd64.
Preparing to unpack .../18-openjdk-11-jre_11.0.32+9-1ubuntu1~24.04_amd64.deb ...
Unpacking openjdk-11-jre:amd64 (11.0.32+9-1ubuntu1~24.04) ...
Selecting previously unselected package openjdk-11-jdk-headless:amd64.
Preparing to unpack .../19-openjdk-11-jdk-headless_11.0.32+9-1ubuntu1~24.04_amd64.deb ...
Unpacking openjdk-11-jdk-headless:amd64 (11.0.32+9-1ubuntu1~24.04) ...
Selecting previously unselected package openjdk-11-jdk:amd64.
Preparing to unpack .../20-openjdk-11-jdk_11.0.32+9-1ubuntu1~24.04_amd64.deb ...
Unpacking openjdk-11-jdk:amd64 (11.0.32+9-1ubuntu1~24.04) ...
Setting up session-migration (0.3.9build1) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1.1build1) ...
Setting up openjdk-11-jre-headless:amd64 (11.0.32+9-1ubuntu1~24.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
Setting up libxxf86dga1:amd64 (2:1.1.5-1build1) ...
Setting up libxt-dev:amd64 (1:1.2.1-1.2build1) ...
Setting up libatspi2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up fonts-dejavu-mono (2.37-8) ...
Setting up fonts-dejavu-core (2.37-8) ...
Setting up fonts-dejavu-extra (2.37-8) ...
Setting up at-spi2-common (2.52.0-1build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build3) ...
Setting up gsettings-desktop-schemas (46.1-0ubuntu1) ...
Setting up libatk1.0-0t64:amd64 (2.52.0-1build1) ...
Setting up x11-utils (7.7+6build2) ...
Setting up libatk-wrapper-java (0.40.0-3build2) ...
Setting up libatk-bridge2.0-0t64:amd64 (2.52.0-1build1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.40.0-3build2) ...
Processing triggers for fontconfig (2.15.0-1.1ubuntu2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.8) ...
/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libglib2.0-0t64:amd64 (2.80.0-6ubuntu3.8) ...
Setting up at-spi2-core (2.52.0-1build1) ...
Processing triggers for ca-certificates-java (20240118) ...
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
done.
Setting up openjdk-11-jre:amd64 (11.0.32+9-1ubuntu1~24.04) ...
Setting up openjdk-11-jdk-headless:amd64 (11.0.32+9-1ubuntu1~24.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jaotc to provide /usr/bin/jaotc (jaotc) in auto mode
Setting up openjdk-11-jdk:amd64 (11.0.32+9-1ubuntu1~24.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
Java 11 installation completed.

In [50]:
! /usr/lib/jvm/java-11-openjdk-amd64/bin/java -version

openjdk version "11.0.32" 2026-07-21
OpenJDK Runtime Environment (build 11.0.32+9-post-1ubuntu1-24.04-Ubuntu)
OpenJDK 64-Bit Server VM (build 11.0.32+9-post-1ubuntu1-24.04-Ubuntu, mixed mode, sharing)

In [51]:
import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"

print("JAVA_HOME =", os.environ["JAVA_HOME"])

JAVA_HOME = /usr/lib/jvm/java-11-openjdk-amd64

In [52]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export HIVE_HOME=/content/hive && \
/content/hive/bin/hive -e "SHOW DATABASES;"

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = 13da7e80-2ba4-4ce9-9ae9-389f224f906a
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:413)
	at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:389)
	at org.apache.hadoop.hive.cli.CliSessionState.<init>(CliSessionState.java:60)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:705)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:683)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:328)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:241)

In [53]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
echo "JAVA_HOME=$JAVA_HOME" && \
$JAVA_HOME/bin/java -version && \
/content/hive/bin/hive --version

JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
openjdk version "11.0.32" 2026-07-21
OpenJDK Runtime Environment (build 11.0.32+9-post-1ubuntu1-24.04-Ubuntu)
OpenJDK 64-Bit Server VM (build 11.0.32+9-post-1ubuntu1-24.04-Ubuntu, mixed mode, sharing)
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive 3.1.3
Git git://MacBook-Pro.fios-router.home/Users/ngangam/commit/hive -r 4df4d75bf1e16fe0af75aad0b4179c34c07fc975
Compiled by ngangam on Sun Apr 3 16:58:16 EDT 2022
From source with checksum 5da234766db5dfbe3e92926c9bbab2af

In [54]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export PATH=$JAVA_HOME/bin:$PATH && \
which java && \
java -version && \
echo "Hive JAVA_HOME: $JAVA_HOME"

/usr/lib/jvm/java-11-openjdk-amd64/bin/java
openjdk version "11.0.32" 2026-07-21
OpenJDK Runtime Environment (build 11.0.32+9-post-1ubuntu1-24.04-Ubuntu)
OpenJDK 64-Bit Server VM (build 11.0.32+9-post-1ubuntu1-24.04-Ubuntu, mixed mode, sharing)
Hive JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

In [55]:
!grep -E "HADOOP_HOME|JAVA_HOME|HIVE_AUX_JARS_PATH" /content/hive/bin/hive | head -20

if [ -d "${HIVE_AUX_JARS_PATH}" ]; then
  hive_aux_jars_abspath=`cd ${HIVE_AUX_JARS_PATH} && pwd`
elif [ "${HIVE_AUX_JARS_PATH}" != "" ]; then
  HIVE_AUX_JARS_PATH=`echo $HIVE_AUX_JARS_PATH | sed 's/,/:/g'`
      HIVE_AUX_JARS_PATH=`cygpath -p -w "$HIVE_AUX_JARS_PATH"`
      HIVE_AUX_JARS_PATH=`echo $HIVE_AUX_JARS_PATH | sed 's/;/,/g'`
  AUX_CLASSPATH=${AUX_CLASSPATH}:${HIVE_AUX_JARS_PATH}
  AUX_PARAM="file://$(echo ${HIVE_AUX_JARS_PATH} | sed 's/:/,file:\/\//g')"
# supress the HADOOP_HOME warnings in 1.x.x
export HADOOP_HOME_WARN_SUPPRESS=true
# HADOOP_HOME env variable overrides hadoop in the path
HADOOP_HOME=${HADOOP_HOME:-${HADOOP_PREFIX:-$HADOOP_DIR}}
if [ "$HADOOP_HOME" == "" ]; then
  echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";
for f in ${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-distcp-*.jar; do
HADOOP=$HADOOP_HOME/bin/hadoop
  echo "Cannot find hadoop installation: \$HADOOP_HOME or \$HADOOP_PREFIX must be set or hadoop must be in the path";

In [56]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
echo "JAVA_HOME=$JAVA_HOME" && \
echo "HADOOP_HOME=$HADOOP_HOME" && \
echo "JAVA=$(which java)" && \
echo "JAVA_VERSION:" && \
java -version

JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
HADOOP_HOME=/content/hadoop
JAVA=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
JAVA_VERSION:
openjdk version "11.0.32" 2026-07-21
OpenJDK Runtime Environment (build 11.0.32+9-post-1ubuntu1-24.04-Ubuntu)
OpenJDK 64-Bit Server VM (build 11.0.32+9-post-1ubuntu1-24.04-Ubuntu, mixed mode, sharing)

In [57]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/schematool -dbType derby -info

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Metastore connection URL:	 jdbc:derby:;databaseName=/content/hive_metastore_db;create=true
Metastore Connection Driver :	 org.apache.derby.jdbc.EmbeddedDriver
Metastore connection User:	 APP
org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version, Cause:Table/View 'VERSION' does not exist.
Use --verbose for detailed stacktrace.
*** schemaTool failed ***

In [58]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/schematool -dbType derby -initSchema

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Metastore connection URL:	 jdbc:derby:;databaseName=/content/hive_metastore_db;create=true
Metastore Connection Driver :	 org.apache.derby.jdbc.EmbeddedDriver
Metastore connection User:	 APP
Starting metastore schema initialization to 3.1.0
Initialization script hive-schema-3.1.0.derby.sql

































































































































































































































Initialization script completed
schemaTool completed

In [59]:
!rm -rf /content/hive_metastore_db

In [60]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/schematool -dbType derby -initSchema

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Metastore connection URL:	 jdbc:derby:;databaseName=/content/hive_metastore_db;create=true
Metastore Connection Driver :	 org.apache.derby.jdbc.EmbeddedDriver
Metastore connection User:	 APP
Starting metastore schema initialization to 3.1.0
Initialization script hive-schema-3.1.0.derby.sql

































































































































































































































Initialization script completed
schemaTool completed

In [61]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/schematool -dbType derby -initSchema

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Metastore connection URL:	 jdbc:derby:;databaseName=/content/hive_metastore_db;create=true
Metastore Connection Driver :	 org.apache.derby.jdbc.EmbeddedDriver
Metastore connection User:	 APP
Starting metastore schema initialization to 3.1.0
Initialization script hive-schema-3.1.0.derby.sql


Error: FUNCTION 'NUCLEUS_ASCII' already exists. (state=X0Y68,code=30000)
org.apache.hadoop.hive.metastore.HiveMetaException: Schema initialization FAILED! Metastore state would be inconsistent !!
Underlying cause: java.io.IOException : Schema script failed, errorcode 2
Use --verbose for detailed stacktrace.
*** schemaTool failed ***

In [62]:
!ls -lah /content/hive_metastore_db

total 44K
drwxr-xr-x 5 root root 4.0K Sep 12 06:36 .
drwxr-xr-x 1 root root 4.0K Sep 12 06:36 ..
-rw-r--r-- 1 root root    4 Sep 12 06:36 dbex.lck
-rw-r--r-- 1 root root   38 Sep 12 06:36 db.lck
drwxr-xr-x 2 root root 4.0K Sep 12 06:36 log
-rw-r--r-- 1 root root  608 Sep 12 06:36 README_DO_NOT_TOUCH_FILES.txt
drwxr-xr-x 2 root root  12K Sep 12 06:36 seg0
-rw-r--r-- 1 root root  905 Sep 12 06:36 service.properties
drwxr-xr-x 2 root root 4.0K Sep 12 06:36 tmp

In [63]:
!jps

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
3025 DataNode
2929 NameNode
6350 Jps

In [64]:
!rm -rf /content/hive_metastore_db
!ls -ld /content/hive_metastore_db

ls: cannot access '/content/hive_metastore_db': No such file or directory

In [65]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/schematool -dbType derby -initSchema

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Metastore connection URL:	 jdbc:derby:;databaseName=/content/hive_metastore_db;create=true
Metastore Connection Driver :	 org.apache.derby.jdbc.EmbeddedDriver
Metastore connection User:	 APP
Starting metastore schema initialization to 3.1.0
Initialization script hive-schema-3.1.0.derby.sql

































































































































































































































Initialization script completed
schemaTool completed

In [66]:
!export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/hive -e "SHOW DATABASES;"

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = 5dfb4dda-4657-4d20-818a-7699396d00a8
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:413)
	at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:389)
	at org.apache.hadoop.hive.cli.CliSessionState.<init>(CliSessionState.java:60)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:705)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:683)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:328)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:241)

In [67]:
!ls -d /usr/lib/jvm/* | grep -E "java-8|openjdk-8"

In [68]:
!apt-get update -qq
!apt-get install -y openjdk-8-jdk

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libgail-common libgail18t64 libgtk2.0-0t64 libgtk2.0-bin libgtk2.0-common
  librsvg2-common openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
Suggested packages:
  gvfs openjdk-8-demo openjdk-8-source visualvm libnss-mdns fonts-nanum
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  libgail-common libgail18t64 libgtk2.0-0t64 libgtk2.0-bin libgtk2.0-common
  librsvg2-common openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre
  openjdk-8-jre-headless
0 upgraded, 10 newly installed, 0 to remove and 30 not upgraded.
Need to get 46.0 MB of archives.
After this operation, 155 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk2.0-common all 2.24.33-4ubuntu1.1 [127 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk2.0-0t64 amd64 2.24.33-4ubuntu1.1 [2,006 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgail18t64 amd64 2.24.33-4ubuntu1.1 [15.9 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgail-common amd64 2.24.33-4ubuntu1.1 [126 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libgtk2.0-bin amd64 2.24.33-4ubuntu1.1 [7,954 B]
Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 librsvg2-common amd64 2.58.0+dfsg-1build1 [11.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 openjdk-8-jre-headless amd64 8u502-ga~us1-0ubuntu1~24.04 [30.7 MB]
Get:8 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 openjdk-8-jre amd64 8u502-ga~us1-0ubuntu1~24.04 [74.0 kB]
Get:9 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 openjdk-8-jdk-headless amd64 8u502-ga~us1-0ubuntu1~24.04 [8,852 kB]
Get:10 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 openjdk-8-jdk amd64 8u502-ga~us1-0ubuntu1~24.04 [4,104 kB]
Fetched 46.0 MB in 3s (16.2 MB/s)
Selecting previously unselected package libgtk2.0-common.
(Reading database ... 123856 files and directories currently installed.)
Preparing to unpack .../0-libgtk2.0-common_2.24.33-4ubuntu1.1_all.deb ...
Unpacking libgtk2.0-common (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libgtk2.0-0t64:amd64.
Preparing to unpack .../1-libgtk2.0-0t64_2.24.33-4ubuntu1.1_amd64.deb ...
Unpacking libgtk2.0-0t64:amd64 (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libgail18t64:amd64.
Preparing to unpack .../2-libgail18t64_2.24.33-4ubuntu1.1_amd64.deb ...
Unpacking libgail18t64:amd64 (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libgail-common:amd64.
Preparing to unpack .../3-libgail-common_2.24.33-4ubuntu1.1_amd64.deb ...
Unpacking libgail-common:amd64 (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package libgtk2.0-bin.
Preparing to unpack .../4-libgtk2.0-bin_2.24.33-4ubuntu1.1_amd64.deb ...
Unpacking libgtk2.0-bin (2.24.33-4ubuntu1.1) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../5-librsvg2-common_2.58.0+dfsg-1build1_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.58.0+dfsg-1build1) ...
Selecting previously unselected package openjdk-8-jre-headless:amd64.
Preparing to unpack .../6-openjdk-8-jre-headless_8u502-ga~us1-0ubuntu1~24.04_amd64.deb ...
Unpacking openjdk-8-jre-headless:amd64 (8u502-ga~us1-0ubuntu1~24.04) ...
Selecting previously unselected package openjdk-8-jre:amd64.
Preparing to unpack .../7-openjdk-8-jre_8u502-ga~us1-0ubuntu1~24.04_amd64.deb ...
Unpacking openjdk-8-jre:amd64 (8u502-ga~us1-0ubuntu1~24.04) ...
Selecting previously unselected package openjdk-8-jdk-headless:amd64.
Preparing to unpack .../8-openjdk-8-jdk-headless_8u502-ga~us1-0ubuntu1~24.04_amd64.deb ...
Unpacking openjdk-8-jdk-headless:amd64 (8u502-ga~us1-0ubuntu1~24.04) ...
Selecting previously unselected package openjdk-8-jdk:amd64.
Preparing to unpack .../9-openjdk-8-jdk_8u502-ga~us1-0ubuntu1~24.04_amd64.deb ...
Unpacking openjdk-8-jdk:amd64 (8u502-ga~us1-0ubuntu1~24.04) ...
Setting up openjdk-8-jre-headless:amd64 (8u502-ga~us1-0ubuntu1~24.04) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/orbd to provide /usr/bin/orbd (orbd) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/servertool to provide /usr/bin/servertool (servertool) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode
Setting up librsvg2-common:amd64 (2.58.0+dfsg-1build1) ...
Setting up libgtk2.0-common (2.24.33-4ubuntu1.1) ...
Setting up libgtk2.0-0t64:amd64 (2.24.33-4ubuntu1.1) ...
Setting up libgail18t64:amd64 (2.24.33-4ubuntu1.1) ...
Setting up libgtk2.0-bin (2.24.33-4ubuntu1.1) ...
Setting up libgail-common:amd64 (2.24.33-4ubuntu1.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.8) ...
/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.10+dfsg-3ubuntu3.3) ...
Processing triggers for ca-certificates-java (20240118) ...
[0.003s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.003s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
done.
Setting up openjdk-8-jre:amd64 (8u502-ga~us1-0ubuntu1~24.04) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/policytool to provide /usr/bin/policytool (policytool) in auto mode
Setting up openjdk-8-jdk-headless:amd64 (8u502-ga~us1-0ubuntu1~24.04) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/clhsdb to provide /usr/bin/clhsdb (clhsdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/extcheck to provide /usr/bin/extcheck (extcheck) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/hsdb to provide /usr/bin/hsdb (hsdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/idlj to provide /usr/bin/idlj (idlj) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/javah to provide /usr/bin/javah (javah) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jhat to provide /usr/bin/jhat (jhat) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/jsadebugd to provide /usr/bin/jsadebugd (jsadebugd) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/native2ascii to provide /usr/bin/native2ascii (native2ascii) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/schemagen to provide /usr/bin/schemagen (schemagen) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/wsgen to provide /usr/bin/wsgen (wsgen) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/wsimport to provide /usr/bin/wsimport (wsimport) in auto mode
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/xjc to provide /usr/bin/xjc (xjc) in auto mode
Setting up openjdk-8-jdk:amd64 (8u502-ga~us1-0ubuntu1~24.04) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/bin/appletviewer to provide /usr/bin/appletviewer (appletviewer) in auto mode
Processing triggers for libc-bin (2.39-0ubuntu8.8) ...
/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

In [69]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \
export PATH=$JAVA_HOME/bin:$PATH && \
java -version

openjdk version "1.8.0_502"
OpenJDK Runtime Environment (build 1.8.0_502-8u502-ga~us1-0ubuntu1~24.04-b07)
OpenJDK 64-Bit Server VM (build 25.502-b07, mixed mode)

In [70]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/hive -e "SHOW DATABASES;"

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = 679c6fcf-b25b-4f4f-834a-3d95a06bc9b4
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:413)
	at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:389)
	at org.apache.hadoop.hive.cli.CliSessionState.<init>(CliSessionState.java:60)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:705)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:683)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:328)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:241)

In [71]:
!grep -n "JAVA_HOME" /content/hadoop/etc/hadoop/hadoop-env.sh

37:#  JAVA_HOME=/usr/java/testing hdfs dfs -ls
47:# Technically, the only required environment variable is JAVA_HOME.
54:# export JAVA_HOME=
437:export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64

In [72]:
!sed -i 's|export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64|export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64|' /content/hadoop/etc/hadoop/hadoop-env.sh

In [73]:
!grep -n "export JAVA_HOME" /content/hadoop/etc/hadoop/hadoop-env.sh

54:# export JAVA_HOME=
437:export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

In [74]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/hive -e "SHOW DATABASES;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = dbcd3a1d-d0e8-4875-b89e-7784cf725d00

Logging initialized using configuration in jar:file:/content/hive/lib/hive-common-3.1.3.jar!/hive-log4j2.properties Async: true
Exception in thread "main" java.lang.RuntimeException: The dir: hdfs://localhost:9000/tmp/hive on HDFS should be writable. Current permissions are: rwxr-xr-x
	at org.apache.hadoop.hive.ql.exec.Utilities.ensurePathIsWritable(Utilities.java:4501)
	at org.apache.hadoop.hive.ql.session.SessionState.createRootHDFSDir(SessionState.java:760)
	at org.apache.hadoop.hive.ql.session.SessionState.createSessionDirs(SessionState.java:701)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:627)
	at org.apache.hadoop.hive.ql.session.SessionState.beginStart(SessionState.java:591)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:747)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:683)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:328)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:241)

In [75]:
!export HADOOP_HOME=/content/hadoop && \
export PATH=$HADOOP_HOME/bin:$PATH && \
hdfs dfs -chmod 777 /tmp/hive

In [76]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/hive -e "SHOW DATABASES;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = 17c0a92d-2926-4884-a140-2fea9f96daa9

Logging initialized using configuration in jar:file:/content/hive/lib/hive-common-3.1.3.jar!/hive-log4j2.properties Async: true
Hive Session ID = 33564215-fc7e-4b10-b309-c12db5f144af
OK
default
Time taken: 1.375 seconds, Fetched: 1 row(s)

In [77]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/hive -e "CREATE DATABASE IF NOT EXISTS road_accident_db; SHOW DATABASES;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = cb643538-4ddb-4de9-9bcf-ff526f29c26b

Logging initialized using configuration in jar:file:/content/hive/lib/hive-common-3.1.3.jar!/hive-log4j2.properties Async: true
Hive Session ID = abf88c72-5473-4a4b-9efd-15322ff31d0a
OK
Time taken: 1.374 seconds
OK
default
road_accident_db
Time taken: 0.305 seconds, Fetched: 2 row(s)

In [78]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export HADOOP_HOME=/content/hadoop && export HIVE_HOME=/content/hive && export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && /content/hive/bin/hive -e "USE road_accident_db; CREATE EXTERNAL TABLE IF NOT EXISTS accident_data (latitude DOUBLE, longitude DOUBLE, hour INT, temperature DOUBLE, visibility INT, traffic_density INT, weather INT, road_type INT, weekend INT, peak_hour INT, risk_score DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION 'hdfs://localhost:9000/road_accidents';"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = a3e58619-0d9b-45fd-aea0-62f0ee6cc38b

Logging initialized using configuration in jar:file:/content/hive/lib/hive-common-3.1.3.jar!/hive-log4j2.properties Async: true
Hive Session ID = 9a67f18c-70e7-48da-b5b4-8e60e5c56930
OK
Time taken: 1.377 seconds
OK
Time taken: 1.277 seconds

In [79]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && export HADOOP_HOME=/content/hadoop && export HIVE_HOME=/content/hive && export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && /content/hive/bin/hive -e "USE road_accident_db; CREATE EXTERNAL TABLE IF NOT EXISTS accident_data (latitude DOUBLE, longitude DOUBLE, hour INT, temperature DOUBLE, visibility INT, traffic_density INT, weather INT, road_type INT, weekend INT, peak_hour INT, risk_score DOUBLE) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION 'hdfs://localhost:9000/road_accidents';"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = 695e4954-9a0e-4f3d-afc3-441191ed3b44

Logging initialized using configuration in jar:file:/content/hive/lib/hive-common-3.1.3.jar!/hive-log4j2.properties Async: true
Hive Session ID = 2f60eb59-5e14-440b-a550-112ce4862d0f
OK
Time taken: 1.031 seconds
OK
Time taken: 0.604 seconds

In [80]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/hive -e "USE road_accident_db; SELECT * FROM accident_data LIMIT 5;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = a336dcba-b990-4055-9454-06249c6991d5

Logging initialized using configuration in jar:file:/content/hive/lib/hive-common-3.1.3.jar!/hive-log4j2.properties Async: true
Hive Session ID = 2e7c50d8-7153-4561-91f8-79e6f6b49bf8
OK
Time taken: 1.051 seconds
OK
NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL
13.014856	77.553069	14	14.2	2	2	0	1	0	0	0.752
13.039986	77.612158	19	27.4	1	0	0	2	0	1	0.5782
12.905146	77.742477	10	36.7	1	2	2	1	1	1	0.98
12.953085	77.545456	4	40.4	2	2	0	0	0	0	0.8665
Time taken: 3.058 seconds, Fetched: 5 row(s)

In [81]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/hive -e "USE road_accident_db; SELECT COUNT(*) FROM accident_data;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = 5a7481de-15d2-40bb-ae40-f7ddba532b3e

Logging initialized using configuration in jar:file:/content/hive/lib/hive-common-3.1.3.jar!/hive-log4j2.properties Async: true
Hive Session ID = 53495391-9124-4465-8214-4ec47b681346
OK
Time taken: 1.118 seconds
Query ID = root_20260912063948_2dfcb4b3-11c9-4c8c-b7cd-06ddd04bb84e
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Job running in-process (local Hadoop)
2026-09-12 06:39:54,823 Stage-1 map = 0%,  reduce = 0%
Ended Job = job_local1706517508_0001 with errors
Error during job, obtaining debugging information...
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched:
Stage-Stage-1:  HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec

In [82]:
!export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && \
export HADOOP_HOME=/content/hadoop && \
export HIVE_HOME=/content/hive && \
export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HIVE_HOME/bin:$PATH && \
/content/hive/bin/hive -e "USE road_accident_db; CREATE OR REPLACE VIEW accident_clean AS SELECT * FROM accident_data WHERE latitude IS NOT NULL AND longitude IS NOT NULL; SELECT COUNT(*) FROM accident_clean;"

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/content/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/content/hadoop/share/hadoop/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Hive Session ID = 6c581326-cc9a-4d28-8ec7-b07914bcd09c

Logging initialized using configuration in jar:file:/content/hive/lib/hive-common-3.1.3.jar!/hive-log4j2.properties Async: true
Hive Session ID = 602754bf-3639-483b-93a1-82bd48e2857f
OK
Time taken: 1.052 seconds
OK
Time taken: 3.444 seconds
Query ID = root_20260912064020_04bf1511-58e8-4505-90b1-93a74266171a
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapreduce.job.reduces=<number>
Job running in-process (local Hadoop)
2026-09-12 06:40:26,820 Stage-1 map = 0%,  reduce = 0%
2026-09-12 06:40:27,854 Stage-1 map = 100%,  reduce = 0%
2026-09-12 06:40:28,866 Stage-1 map = 100%,  reduce = 100%
Ended Job = job_local1699257630_0001
MapReduce Jobs Launched:
Stage-Stage-1:  HDFS Read: 327442 HDFS Write: 0 SUCCESS
Total MapReduce CPU Time Spent: 0 msec
OK
3500
Time taken: 8.272 seconds, Fetched: 1 row(s)

In [84]:
!export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && \
export PATH=$JAVA_HOME/bin:$PATH && \
java -version && \
spark-submit --version

[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
openjdk version "21.0.12" 2026-07-21
OpenJDK Runtime Environment (build 21.0.12+8-1-24.04-Ubuntu)
OpenJDK 64-Bit Server VM (build 21.0.12+8-1-24.04-Ubuntu, mixed mode, sharing)
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup memory controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
[0.001s][warning][os,container] Cgroup cpu controller path at '/sys/fs/cgroup' seems to have moved to '/../../jupyter-children', detected limits won't be accurate
WARNING: Using incubator modules: jdk.incubator.vector
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 4.0.4
      /_/

Using Scala version 2.13.16, OpenJDK 64-Bit Server VM, 21.0.12
Branch HEAD
Compiled by user holden on 2026-07-12T04:41:54Z
Revision c7d67e3f5d4c9d88a480367b44fc54d26adf99ab
Url https://github.com/apache/spark
Type --help for more information.

In [85]:
import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-21-openjdk-amd64"

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("RoadAccidentAnalysis") \
    .master("local[*]") \
    .getOrCreate()

print("Spark version:", spark.version)

Spark version: 4.0.4

In [87]:
accident_df = spark.read \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .csv("hdfs://localhost:9000/road_accidents/accident_dataset.csv")

print("Total records:", accident_df.count())
accident_df.show(5)

Total records: 3500
+---------+---------+----+-----------+----------+---------------+-------+---------+-------+---------+----------+
| latitude|longitude|hour|temperature|visibility|traffic_density|weather|road_type|weekend|peak_hour|risk_score|
+---------+---------+----+-----------+----------+---------------+-------+---------+-------+---------+----------+
|13.014856|77.553069|  14|       14.2|         2|              2|      0|        1|      0|        0|     0.752|
|13.039986|77.612158|  19|       27.4|         1|              0|      0|        2|      0|        1|    0.5782|
|12.905146|77.742477|  10|       36.7|         1|              2|      2|        1|      1|        1|      0.98|
|12.953085|77.545456|   4|       40.4|         2|              2|      0|        0|      0|        0|    0.8665|
|12.916933|77.603683|   0|       15.2|         2|              0|      0|        0|      0|        0|    0.7057|
+---------+---------+----+-----------+----------+---------------+-------+---------+-------+---------+----------+
only showing top 5 rows

In [88]:
accident_df.describe(
    "hour",
    "temperature",
    "visibility",
    "traffic_density",
    "risk_score"
).show()

+-------+-----------------+------------------+------------------+------------------+-------------------+
|summary|             hour|       temperature|        visibility|   traffic_density|         risk_score|
+-------+-----------------+------------------+------------------+------------------+-------------------+
|  count|             3500|              3500|              3500|              3500|               3500|
|   mean|           11.478|26.878400000000028|             1.276|0.9585714285714285| 0.7874232000000035|
| stddev|6.925383268061449| 8.648012408452455|0.7604439070016359|0.7428794801436747|0.18326941055101176|
|    min|                0|              12.0|                 0|                 0|             0.1664|
|    max|               23|              42.0|                 2|                 2|               0.98|
+-------+-----------------+------------------+------------------+------------------+-------------------+

In [89]:
high_risk_df = accident_df.orderBy(
    accident_df["risk_score"].desc()
).limit(10)

high_risk_df.show(truncate=False)

+---------+---------+----+-----------+----------+---------------+-------+---------+-------+---------+----------+
|latitude |longitude|hour|temperature|visibility|traffic_density|weather|road_type|weekend|peak_hour|risk_score|
+---------+---------+----+-----------+----------+---------------+-------+---------+-------+---------+----------+
|13.001177|77.567933|1   |40.8       |2         |1              |1      |0        |1      |0        |0.98      |
|12.905146|77.742477|10  |36.7       |1         |2              |2      |1        |1      |1        |0.98      |
|12.908434|77.611764|10  |29.1       |1         |2              |0      |1        |0      |1        |0.98      |
|13.012439|77.598788|21  |27.9       |1         |2              |2      |0        |0      |0        |0.98      |
|13.081818|77.581635|8   |18.4       |1         |1              |2      |1        |0      |1        |0.98      |
|12.916322|77.584997|4   |19.7       |2         |1              |2      |0        |0      |0        |0.98      |
|12.926306|77.678515|17  |30.7       |0         |2              |0      |1        |0      |1        |0.98      |
|12.913305|77.615457|17  |13.1       |0         |0              |2      |0        |1      |1        |0.98      |
|12.903769|77.67669 |3   |31.8       |1         |1              |1      |1        |0      |0        |0.98      |
|12.961659|77.592403|13  |16.9       |1         |2              |2      |0        |0      |0        |0.98      |
+---------+---------+----+-----------+----------+---------------+-------+---------+-------+---------+----------+

In [90]:
from pyspark.sql.functions import avg

risk_by_hour = accident_df.groupBy("hour") \
    .agg(avg("risk_score").alias("average_risk")) \
    .orderBy("hour")

risk_by_hour.show(24)

+----+------------------+
|hour|      average_risk|
+----+------------------+
|   0|0.8781774999999998|
|   1|0.8659600000000004|
|   2|0.8611471014492759|
|   3|0.8714622516556293|
|   4|0.8747187050359718|
|   5|0.7259111888111891|
|   6|0.6738083916083916|
|   7|0.7500496503496502|
|   8|0.8406360544217693|
|   9|0.8554209150326804|
|  10|0.8212111940298508|
|  11|0.6868061538461542|
|  12|0.6951981012658227|
|  13|0.7294339999999999|
|  14|0.7111679999999996|
|  15|0.7275538888888892|
|  16|0.7195070921985816|
|  17|0.8158107913669069|
|  18|0.8183630573248412|
|  19|0.8374056000000005|
|  20|0.8457325581395352|
|  21|0.7128527777777779|
|  22|0.7177945578231294|
|  23| 0.873586363636364|
+----+------------------+

In [91]:
from pyspark.sql.functions import round, avg, count, max

black_spots = accident_df \
    .withColumn("lat_zone", round("latitude", 3)) \
    .withColumn("lon_zone", round("longitude", 3)) \
    .groupBy("lat_zone", "lon_zone") \
    .agg(
        count("*").alias("record_count"),
        avg("risk_score").alias("average_risk"),
        max("risk_score").alias("maximum_risk")
    ) \
    .orderBy("average_risk", ascending=False) \
    .limit(20)

black_spots.show(20, truncate=False)

+--------+--------+------------+------------+------------+
|lat_zone|lon_zone|record_count|average_risk|maximum_risk|
+--------+--------+------------+------------+------------+
|12.898  |77.618  |1           |0.98        |0.98        |
|13.009  |77.563  |1           |0.98        |0.98        |
|12.993  |77.545  |1           |0.98        |0.98        |
|13.043  |77.604  |1           |0.98        |0.98        |
|12.961  |77.596  |1           |0.98        |0.98        |
|12.965  |77.596  |1           |0.98        |0.98        |
|12.98   |77.603  |2           |0.98        |0.98        |
|12.989  |77.542  |1           |0.98        |0.98        |
|12.936  |77.69   |1           |0.98        |0.98        |
|12.971  |77.598  |1           |0.98        |0.98        |
|12.909  |77.606  |1           |0.98        |0.98        |
|13.098  |77.506  |1           |0.98        |0.98        |
|12.956  |77.564  |1           |0.98        |0.98        |
|12.956  |77.61   |1           |0.98        |0.98        |
|12.904  |77.598  |1           |0.98        |0.98        |
|13.054  |77.589  |1           |0.98        |0.98        |
|12.921  |77.667  |1           |0.98        |0.98        |
|13.04   |77.624  |1           |0.98        |0.98        |
|13.052  |77.619  |1           |0.98        |0.98        |
|12.993  |77.553  |2           |0.98        |0.98        |
+--------+--------+------------+------------+------------+

In [92]:
risk_by_traffic = accident_df.groupBy("traffic_density") \
    .agg(
        count("*").alias("record_count"),
        avg("risk_score").alias("average_risk")
    ) \
    .orderBy("traffic_density")

risk_by_traffic.show()

+---------------+------------+------------------+
|traffic_density|record_count|      average_risk|
+---------------+------------+------------------+
|              0|        1041|0.6799221902017305|
|              1|        1563|0.7998916186820249|
|              2|         896|0.8905709821428619|
+---------------+------------+------------------+

In [93]:
risk_by_weather = accident_df.groupBy("weather") \
    .agg(
        count("*").alias("record_count"),
        avg("risk_score").alias("average_risk")
    ) \
    .orderBy("weather")

risk_by_weather.show()

+-------+------------+------------------+
|weather|record_count|      average_risk|
+-------+------------+------------------+
|      0|        2115|0.7082052009456264|
|      1|         505|0.8763918811881217|
|      2|         880|0.9267605681818256|
+-------+------------+------------------+

In [94]:
risk_by_road = accident_df.groupBy("road_type") \
    .agg(
        count("*").alias("record_count"),
        avg("risk_score").alias("average_risk")
    ) \
    .orderBy("road_type")

risk_by_road.show()

+---------+------------+------------------+
|road_type|record_count|      average_risk|
+---------+------------+------------------+
|        0|        1245|0.8215366265060277|
|        1|        1556|0.7795760925449906|
|        2|         699|0.7441311874105878|
+---------+------------+------------------+

In [95]:
black_spots_final = accident_df \
    .withColumn("lat_zone", round("latitude", 3)) \
    .withColumn("lon_zone", round("longitude", 3)) \
    .groupBy("lat_zone", "lon_zone") \
    .agg(
        count("*").alias("accident_records"),
        avg("risk_score").alias("average_risk"),
        max("risk_score").alias("maximum_risk")
    ) \
    .filter("accident_records >= 3") \
    .orderBy("average_risk", ascending=False)

black_spots_final.show(20, truncate=False)

+--------+--------+----------------+------------------+------------+
|lat_zone|lon_zone|accident_records|average_risk      |maximum_risk|
+--------+--------+----------------+------------------+------------+
|12.933  |77.698  |3               |0.9443666666666667|0.98        |
|13.003  |77.555  |3               |0.9354666666666667|0.98        |
|13.043  |77.596  |3               |0.9318333333333334|0.98        |
|12.96   |77.597  |3               |0.9020999999999999|0.98        |
|12.971  |77.593  |3               |0.8483999999999999|0.98        |
|13.041  |77.609  |3               |0.8462000000000001|0.9575      |
|12.995  |77.563  |3               |0.8285999999999999|0.98        |
|12.988  |77.565  |3               |0.7942666666666667|0.98        |
|12.92   |77.692  |3               |0.7919333333333333|0.98        |
|12.987  |77.543  |3               |0.7688            |0.98        |
|13.04   |77.593  |4               |0.7588            |0.98        |
|12.921  |77.688  |3               |0.7431            |0.9086      |
|13.008  |77.58   |3               |0.7341333333333333|0.8741      |
|12.956  |77.596  |3               |0.7292000000000001|0.8599      |
|12.921  |77.611  |3               |0.7219000000000001|0.8467      |
|12.962  |77.608  |3               |0.6581666666666667|0.7384      |
+--------+--------+----------------+------------------+------------+

In [96]:
black_spots_final.coalesce(1) \
    .write \
    .mode("overwrite") \
    .option("header", "true") \
    .csv("/content/black_spots_results")

In [97]:
import pandas as pd

result_file = "/content/black_spots_results"

import os
print("Files created:")
print(os.listdir(result_file))

Files created:

FileNotFoundError: [Errno 2] No such file or directory: '/content/black_spots_results'

In [98]:
import os

print(os.listdir("/content"))

['.config', 'hive', 'accident_dataset.csv', 'apache-hive-3.1.3-bin.tar.gz', 'spark-warehouse', 'derby.log', 'hive_tmp', 'hive_metastore_db', 'hadoop', 'hadoop_data', 'hadoop-3.3.6.tar.gz', 'hive_warehouse', 'sample_data']

In [99]:
print("Black-spot records:", black_spots_final.count())
black_spots_final.show(10, truncate=False)

Black-spot records: 16
+--------+--------+----------------+------------------+------------+
|lat_zone|lon_zone|accident_records|average_risk      |maximum_risk|
+--------+--------+----------------+------------------+------------+
|12.933  |77.698  |3               |0.9443666666666667|0.98        |
|13.003  |77.555  |3               |0.9354666666666667|0.98        |
|13.043  |77.596  |3               |0.9318333333333334|0.98        |
|12.96   |77.597  |3               |0.9020999999999999|0.98        |
|12.971  |77.593  |3               |0.8483999999999999|0.98        |
|13.041  |77.609  |3               |0.8462000000000001|0.9575      |
|12.995  |77.563  |3               |0.8285999999999999|0.98        |
|12.988  |77.565  |3               |0.7942666666666667|0.98        |
|12.92   |77.692  |3               |0.7919333333333333|0.98        |
|12.987  |77.543  |3               |0.7688            |0.98        |
+--------+--------+----------------+------------------+------------+
only showing top 10 rows

In [100]:
black_spots_final.toPandas().to_csv(
    "/content/black_spots_results.csv",
    index=False
)

print("Saved successfully!")
print("File:", "/content/black_spots_results.csv")

Saved successfully!
File: /content/black_spots_results.csv

In [101]:
import pandas as pd

black_spots_check = pd.read_csv("/content/black_spots_results.csv")

print("Number of black spots:", len(black_spots_check))
print("\nColumns:")
print(list(black_spots_check.columns))

print("\nData:")
display(black_spots_check)

Number of black spots: 16

Columns:
['lat_zone', 'lon_zone', 'accident_records', 'average_risk', 'maximum_risk']

Data:

    lat_zone  lon_zone  accident_records  average_risk  maximum_risk
0     12.933    77.698                 3      0.944367        0.9800
1     13.003    77.555                 3      0.935467        0.9800
2     13.043    77.596                 3      0.931833        0.9800
3     12.960    77.597                 3      0.902100        0.9800
4     12.971    77.593                 3      0.848400        0.9800
5     13.041    77.609                 3      0.846200        0.9575
6     12.995    77.563                 3      0.828600        0.9800
7     12.988    77.565                 3      0.794267        0.9800
8     12.920    77.692                 3      0.791933        0.9800
9     12.987    77.543                 3      0.768800        0.9800
10    13.040    77.593                 4      0.758800        0.9800
11    12.921    77.688                 3      0.743100        0.9086
12    13.008    77.580                 3      0.734133        0.8741
13    12.956    77.596                 3      0.729200        0.8599
14    12.921    77.611                 3      0.721900        0.8467
15    12.962    77.608                 3      0.658167        0.7384

In [102]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [103]:
import shutil

drive_path = "/content/drive/MyDrive/road_accident_black_spots.csv"

shutil.copy(
    "/content/black_spots_results.csv",
    drive_path
)

print("Black-spot results saved successfully!")
print("Location:", drive_path)

Black-spot results saved successfully!
Location: /content/drive/MyDrive/road_accident_black_spots.csv

In [104]:
import os

path = "/content/drive/MyDrive/road_accident_black_spots.csv"

print("File exists:", os.path.exists(path))
print("File size:", os.path.getsize(path), "bytes")

File exists: True
File size: 673 bytes

In [105]:
import shutil

dataset_drive_path = "/content/drive/MyDrive/road_accident_dataset.csv"

shutil.copy(
    "/content/accident_dataset.csv",
    dataset_drive_path
)

print("Dataset saved successfully!")
print("Location:", dataset_drive_path)

Dataset saved successfully!
Location: /content/drive/MyDrive/road_accident_dataset.csv

In [106]:
import os

dataset_path = "/content/drive/MyDrive/road_accident_dataset.csv"

print("Dataset exists:", os.path.exists(dataset_path))
print("Dataset size:", os.path.getsize(dataset_path), "bytes")

Dataset exists: True
Dataset size: 163721 bytes